### ISSUE TITLE
IP Not Given Problem

### ISSUE THREAD

**Issue by topikuning** [codenexus/lumen-geoip#3]
on line 34, I think it very useless since it will always get empty result. I think it will better if you use $ip = $_SERVER["REMOTE_ADDR"];

**Comment by cringer** [comment]
Lumen uses the phpdotenv library which loads environment variables from .env to getenv(), $_ENV and $_SERVER automagically.  Because of this `getenv('REMOTE_ADDR)` and `$_SERVER["REMOTE__ADDR"]` will return the same value.

With that being said the method call on line 34 was supposed to pull this information but it wasn't.  I have fixed this in the v2.0.0-RC.
